

services:

    postgres:
      image: postgres:13-alpine
      ports:
        - '5432:5432'
      volumes:
        - .var/lib/postgres/data
      environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=9mREsvXDs9GK89Ef




